### ISSUE TITLE
<Tab> already mapped by ~/.local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:127

### ISSUE THREAD

**Issue by steakhutzeee** [kawre/nvim-tabout#4]
Hi, trying to setup neotab i see that using Tab pops a menu with two options: Goto Definition and References.

Checking with `:verbose imap <Tab>` results in:

```
i  <Tab>       * <Lua 1351: ~/.local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:127>
                 cmp.utils.keymap.set_map
        Last set from Lua
```

I set `tabkey to ""` in neotab config and nvim-cmp config this way:

```
     ["<Tab>"] = cmp.mapping(function(fallback)
        if cmp.visible() then
          cmp.select_next_item()
        elseif luasnip.expandable() then
          luasnip.expand()
        elseif luasnip.expand_or_jumpable() then
          luasnip.expand_or_jump()
        elseif check_backspace() then
          --fallback()
          require("neotab").tabout()
        else
          --fallback()
          require("neotab").tabout()
        end
      end, {
        "i",
        "s",
      }),
      ["<S-Tab>"] = cmp.mapping(function(fallback)
        if cmp.visible() then
          cmp.select_prev_item()
        elseif luasnip.jumpable(-1) then
          luasnip.jump(-1)
        else
          require("neotab").tabout()
          --fallback()
        end
      end,
```

Advices on how this can be fixed?
Thanks!

**Comment by kawre** [comment]
I'm not sure I understand, can you post a video? The mapping seem to be correct and working

**Comment by steakhutzeee** [comment]
> I'm not sure I understand, can you post a video? The mapping seem to be correct and working

Thank you for your immediate reply.
Attaching a screen. My cursor is on the opening parens.

![screen](https://github.com/kawre/neotab.nvim/assets/57228102/2d5d9bf3-41e9-4a89-aa8e-404bada12954)

Hitting tab opens the menu instead of jumping.

**Comment by kawre** [comment]
Are you in insert mode when hitting tab?

**Comment by steakhutzeee** [comment]
> Are you in insert mode when hitting tab?

Nope, i was not, sorry for that. In insert mode it works without problems.

**Comment by steakhutzeee** [comment]
I noticed that this works even without setting `tabkey to ""`

**Comment by kawre** [comment]
> I noticed that this works even without setting `tabkey to ""`

I would recommend to set tabkey to `""` if you plan to use tab mapped in `nvim-cmp`. This may work now but if the plugin load order changes, `neotab` might override `<Tab>` in `nvim-cmp` and you will lose all of that functionality. It will save you from a lot of pointless debugging
